### ISSUE TITLE
Elements for a release should be cached

### ISSUE THREAD

**Issue by ebidel** [PolymerLabs/bowerzipper#10]
The zipper backend needs to be way more robust. Elements for a release should be cached and the .zip files should be merged together on the fly. This will also make the download faster.

**Comment by NinoSkopac** [comment]
+1 for this.
ZIp downloader is still broken as of Sep 2015, almost a year after OP.

**Comment by ebidel** [comment]
Hmm it's working me for and it powers our element catalog. Can you clarify
whats not working? What components are you selecting?

**Comment by NinoSkopac** [comment]
My bad, didn't realize this is a bower tracker, I thought the discussion was about ZIP elements downloader, which is indeed broken (there's been a thread about it on Groups for a year also).

**Comment by ebidel** [comment]
To be clear, we're talking about the frontend here? 
http://bowerarchiver.appspot.com/

That is outdated but the underlying service should be working.

**Comment by NinoSkopac** [comment]
No, about elements.polymer-project.org, the "Add to collection" & download as ZIP feature.
Here's the Groups discussion: https://groups.google.com/forum/#!topic/polymer-dev/tYfrFb_ozHg

**Comment by ebidel** [comment]
That thread is about installing zips from Github. I just installed a few
elements from "add to collection" and it worked.

**Comment by NinoSkopac** [comment]
Using bower or download as zip? I don't know about bower, but zip doesn't work. It only downloads a file called "archive" with bytecode.

**Comment by ebidel** [comment]
I did download as zip.

**Comment by NinoSkopac** [comment]
I just tried again, still doesn't work for me
![capture](https://cloud.githubusercontent.com/assets/1783732/9695990/c20838c8-5368-11e5-93b0-636679184fc7.JPG)

Are we on the same page?

**Comment by ebidel** [comment]
Is this windows? wonder if that's the issue.

**Comment by NinoSkopac** [comment]
I'm not sure what you're asking me.

**Comment by notwaldorf** [comment]
I think @ebidel is wondering whether the issue is on Windows (and maybe that the file isn't correctly named `archive.zip`, and the OS doesn't know how to unarchive it). He is testing it on a Mac, where that button downloads an `archive.zip` file, and it works.

Can you look at the downloaded file and double check that you're not hiding extensions, and it isn't called `archive.zip`, please?

**Comment by notwaldorf** [comment]
I just tried this out on Linux, and the file downloaded is `archive.zip`. Do you have an unzip utility installed on your machine (I'm not super sure if Windows comes natively with one)?

**Comment by NinoSkopac** [comment]
Hey @ebidel and @notwaldorf - I'm on Windows 10 running Chrome 45.0.2454.85 (Official Build) m (32-bit), and no, I'm not hiding extensions (but thanks for implying I'm a mongoloid), Windows have had been bundled with zip/unzip utility since Win 7 if I am not mistaken(maybe even Vista), but I use WinRar as an alternative software for that.

Feel free to take a look at my Downloads folder:
![capture](https://cloud.githubusercontent.com/assets/1783732/9698599/67467070-53be-11e5-831b-e5a20fa38872.JPG)

I just tried on my other computer, one running Win 8, Chrome 44 branch, and there, to my surprise - it downloads perfectly with a .zip extension and non garbled contents.

Afterwards, to kind of try to gain more insight, I tried on my laptop, which is running latest build of  Win 7 and Chrome 47 canary (47.0.2500.0), and there, as you probably guessed - it doesn't work, or in other words, your site behaves like on my Win 10 machine.

intradesting

**Comment by ebidel** [comment]
The fact that it works on some machines and not others (and we're not seeing this ourselves across a few different platforms) leads me to believe it's something with your system. Maybe anti-virus software or a chrome extension getting in the way. Closing.
